// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrhryeehhwuwjlxqbnpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yaHJ5ZWVoaHd1d2pseHFibnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzY5NzksImV4cCI6MjA3MDA1Mjk3OX0.0dpVP6nuXgemHs7mMdnK2g6ajP646qO3Vr-JaMskq6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});