// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpvvgpdqntbthvltbhvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwdnZncGRxbnRidGh2bHRiaHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjQzNTYsImV4cCI6MjA3MDE0MDM1Nn0.dNQaV6EfiarNm_AE0UdiMNNojieG0wynh56OZjmdUUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});